name: gausugar
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8  # 최신 CUDA 지원
  - python=3.9
  - pip
  - numpy
  - plyfile
  - tqdm
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch3d=0.7.4
  - scipy
  - scikit-learn
  - jupyterlab
  - ipywidgets
  - open3d
  - plotly
  - matplotlib
  - nodejs
  - rich
  - fvcore
  - iopath
  - pyquaternion
  - xz
  - zlib
  - joblib
  - requests
  - ffmpeg  # 영상 프레임 추출에 필요
  - setuptools
  - ipython
  - dash
  - pandas
  - werkzeug
  - flask
  - libgcc-ng
  - libstdcxx-ng
  - pycparser
  - mkl
  - mkl-service
  - tqdm
  - pip:
      - addict
      - contourpy
      - pymcubes
      - nvdiffrast  # Mesh 가속화용 라이브러리
      - "submodules/diff-gaussian-rasterization"
      - "submodules/simple-knn"
      - "submodules/fused-ssim"
      - opencv-python
